### ISSUE TITLE
Running filters at validation time

### ISSUE THREAD

**Issue by kiwiroy** [reneeb/Mojolicious-Plugin-FormFieldsFromJSON#11]
The ability to run [filters](https://docs.mojolicious.org/Mojolicious/Validator#FILTERS) at validation time by adding a `filters` key to the current `validation` object would be useful.

```json
"validation": {
  "required": "names",
  "filters": ["comma_separated"],
  "size": [1, 10]
}
```

**Comment by reneeb** [comment]
Version 1.03 should hit CPAN in a few minutes....
