### ISSUE TITLE
Tests fail with older Mojolicious versions

### ISSUE THREAD

**Issue by eserte** [reneeb/Mojolicious-Plugin-FormFieldsFromJSON#3]
See http://analysis.cpantesters.org/solved?distv=Mojolicious-Plugin-FormFieldsFromJSON-0.31#mod%3AMojolicious --- tests fail for old Mojolicious (e.g. 5.xx or 6.08) and pass for 6.22 and later.

**Comment by reneeb** [comment]
Current min. required version for Mojolicious is 6.50. Current release has no FAILs (so far).
